version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: figma-mcp-dev
    container_name: figma-mcp-devcontainer
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - cargo_cache:/home/node/.cargo
    ports:
      - "8765:8765"
    environment:
      - NODE_ENV=development
      - GITHUB_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    stdin_open: true
    tty: true
    user: node
    working_dir: /workspace
    command: /bin/bash

volumes:
  node_modules:
  cargo_cache: